# Generated by Django 6.0.7 on 2026-09-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='doacao',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservada'), ('coletada', 'Coletada'), ('a_caminho', 'A caminho'), ('entregue', 'Entregue'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='disponivel', max_length=20),
        ),
    ]
